###############################################################################
#                          Solutech Booking Challenge                         #
###############################################################################
version: '3.1'
services:
    app:
        container_name: booking-app
        image: 'nginx:alpine'
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf'
        ports:
            - '8000:80'
        depends_on:
            - php-fpm
            - mysql
            - redis
            - mailhog
    php-fpm:
        container_name: booking-php-fpm
        build: docker/php-fpm
        working_dir: /application
        volumes:
            - '.:/application'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/fpm/conf.d/99-overrides.ini'
            - './docker/php-fpm/php-ini-overrides.ini:/etc/php/8.4/cli/conf.d/99-overrides.ini'
            - './docker/setup:/setup'

    mysql:
        container_name: booking-mysql
        image: 'mysql:8.0'
        working_dir: /application
        volumes:
            - '.:/application'
            - 'booking-data:/var/lib/mysql'
        environment:
            - MYSQL_ROOT_PASSWORD=secret@santa
            - MYSQL_DATABASE=booking
            - MYSQL_USER=booking
            - MYSQL_PASSWORD=secret@santa
#        ports:
#            - '3306:3306'

    redis:
        container_name: booking-redis
        image: redis:alpine
        restart: unless-stopped
#        ports:
#            - "6379:6379"

#for development only
    mailhog:
        container_name: booking-mailhog
        image: 'mailhog/mailhog:latest'
        ports:
            - '8001:8025'
#            - '1025:1025'

    # DB access via PHP my admin
    phpmyadmin:
        image: phpmyadmin
        container_name: booking-phpmyadmin
        environment:
            - PMA_ARBITRARY=1
        restart: always
        ports:
            - '8002:80'
        depends_on:
            - php-fpm
            - mysql
volumes:
    booking-data:
